services:
  app:
    build:
      context: .
      dockerfile: .docker/app/Dockerfile.prod
    container_name: calendar_app
    ports:
      - '${NGINX_EXT_PORT:-8000}:80'
    working_dir: /var/www
    volumes:
      - storage_data:/var/www/storage
    depends_on:
      - mysql
      - redis
    networks:
      - calendar

  mysql:
    image: mysql:8.0
    container_name: calendar_mysql
    ports:
      - '${MYSQL_EXT_PORT:-3306}:3306'
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-calendar}
      MYSQL_USER: ${DB_USERNAME:-calendar}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-secret}
    volumes:
      - calendar_mysql_data:/var/lib/mysql
    networks:
      - calendar

  redis:
    image: redis:alpine
    container_name: calendar_redis
    command: redis-server --requirepass ${REDIS_PASSWORD:-secret} --appendonly yes
    ports:
      - '${REDIS_EXT_PORT:-6379}:6379'
    volumes:
      - calendar_redis_data:/data
    networks:
      - calendar

networks:
  calendar:

volumes:
  storage_data:
  calendar_mysql_data:
  calendar_redis_data:
