services:
  app:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - mysql
      - redis
    networks:
      - calendar

  node:
    image: node:24-alpine
    working_dir: /var/www
    volumes:
      - ./:/var/www
    profiles:
      - node
    ports:
      - '5173:5173'
    networks:
      - calendar

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - '${NGINX_EXT_PORT:-8000}:80'
    volumes:
      - ./:/var/www
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - calendar

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - '${MYSQL_EXT_PORT:-3306}:3306'
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-calendar}
      MYSQL_USER: ${DB_DATABASE:-calendar}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-secret}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - calendar

  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD:-secret} --appendonly yes
    ports:
      - '${REDIS_EXT_PORT:-6379}:6379'
    volumes:
      - redis_data:/data
    networks:
      - calendar

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    ports:
      - '${MAILPIT_WEB_EXT_PORT:-8025}:8025'
      - '${MAILPIT_SMTP_EXT_PORT:-1025}:1025'
    networks:
      - calendar

networks:
  calendar:

volumes:
  mysql_data:
  redis_data:
